# Generated by Django 3.2 on 2023-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclicktracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='button_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='button_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='link_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
