# Generated by Django 3.2 on 2023-08-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclicktracker', '0003_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
