# Generated by Django 3.2 on 2023-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclicktracker', '0004_alter_website_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='favicon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='first_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
