# Generated by Django 3.2 on 2023-08-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclicktracker', '0005_auto_20230820_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteclick',
            name='website',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='webclicktracker.website'),
            preserve_default=False,
        ),
    ]
