# Generated by Django 3.2 on 2023-08-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclicktracker', '0007_rename_websiteclick_websitepages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Subpage', max_length=100)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webclicktracker.websitepages')),
            ],
        ),
    ]
