# Generated by Django 3.2 on 2023-09-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('subline', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketing_images/')),
                ('headline', models.CharField(max_length=200)),
                ('subline', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpages.contentpage')),
            ],
        ),
    ]
