# Generated by Django 3.2 on 2023-09-07 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contentpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
