# Generated by Django 3.2 on 2023-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpages', '0002_contentpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='og_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
