# Generated by Django 3.2 on 2023-09-08 06:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentpages', '0003_contentpage_og_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='body_text',
        ),
        migrations.AlterField(
            model_name='marketingfield',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
