# Generated by Django 3.2 on 2023-09-08 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentpages', '0004_auto_20230908_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingfield',
            name='creator_user',
            field=models.ForeignKey(default=None, help_text='User that created last translation version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_translation', to=settings.AUTH_USER_MODEL, verbose_name='User translator'),
        ),
    ]
