# Generated by Django 3.2 on 2023-09-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_auto_20230908_1347'),
        ('contentpages', '0006_auto_20230908_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageTranslation',
            fields=[
                ('translation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='translations.translation')),
                ('subline', models.CharField(max_length=200)),
                ('translatable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpages.contentpage')),
            ],
            bases=('translations.translation',),
        ),
    ]
