# Generated by Django 3.2 on 2023-09-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentpages', '0007_contentpagetranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentPageTranslation',
        ),
    ]
