# Generated by Django 3.2 on 2023-09-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
