# Generated by Django 3.2 on 2023-09-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
