# Generated by Django 3.2 on 2023-09-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='save',
            new_name='savings',
        ),
    ]
