# Generated by Django 3.2 on 2023-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_save_product_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='savings',
            new_name='monthly_price_savings',
        ),
        migrations.AddField(
            model_name='product',
            name='savings_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
