# Generated by Django 3.2 on 2023-09-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230903_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_abo',
            field=models.BooleanField(default=True),
        ),
    ]
