# Generated by Django 3.2 on 2023-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_payment_abo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_id',
            field=models.CharField(default='checkout-button', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(default='price_1O6ZIkFJc5Umrifwi3hxGJ74', max_length=100),
        ),
    ]
