# Generated by Django 3.2 on 2023-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20231029_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_id',
            field=models.CharField(blank=True, default='checkout-button', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_id',
            field=models.CharField(blank=True, default='price_1O6ZIkFJc5Umrifwi3hxGJ74', max_length=100),
        ),
    ]
