# Generated by Django 3.2 on 2023-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_campaign',
            field=models.CharField(blank=True, max_length=525),
        ),
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_content',
            field=models.CharField(blank=True, max_length=525),
        ),
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_medium',
            field=models.CharField(blank=True, max_length=525),
        ),
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_source',
            field=models.CharField(blank=True, max_length=525),
        ),
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_tags',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_term',
            field=models.CharField(blank=True, max_length=525),
        ),
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_titel',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
