# Generated by Django 3.2 on 2023-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0002_auto_20230722_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_archivate',
            field=models.BooleanField(default=False),
        ),
    ]
