# Generated by Django 3.2 on 2023-07-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0003_auto_20230722_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
