# Generated by Django 3.2 on 2023-07-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0005_alter_shortcodeclass_shortcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcodeclass',
            old_name='shortcode',
            new_name='short',
        ),
    ]
