# Generated by Django 3.2 on 2023-07-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0007_auto_20230723_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcodeclass',
            old_name='shor',
            new_name='shortcode',
        ),
    ]
