# Generated by Django 3.2 on 2023-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0008_rename_shor_shortcodeclass_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodeclass',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
