# Generated by Django 3.2 on 2023-07-23 19:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('shortcode', '0011_alter_shortcodeclass_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcodeclass',
            name='url_tags',
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='url_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
