# Generated by Django 3.2 on 2023-07-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0012_auto_20230723_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcodeclass',
            name='url_tags',
        ),
    ]
