# Generated by Django 3.2 on 2023-07-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0013_remove_shortcodeclass_url_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcodeclass',
            name='shortcode',
        ),
    ]
