# Generated by Django 3.2 on 2023-07-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0014_remove_shortcodeclass_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='shortcode',
            field=models.CharField(default='uuid1', max_length=15),
        ),
    ]
