# Generated by Django 3.2 on 2023-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0016_alter_shortcodeclass_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodeclass',
            name='url_destination',
            field=models.CharField(max_length=520),
        ),
    ]
