# Generated by Django 3.2 on 2023-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0017_alter_shortcodeclass_url_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='favicon_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
