# Generated by Django 3.2 on 2023-08-17 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0020_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
