# Generated by Django 3.2 on 2023-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0021_auto_20230817_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='alternative_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
