# Generated by Django 3.2 on 2023-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0022_auto_20230828_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='limitation_active',
            field=models.BooleanField(default=False),
        ),
    ]
