# Generated by Django 3.2 on 2023-08-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0024_auto_20230829_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='android',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='android_on_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='geo_targeting_on_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='ios',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='shortcodeclass',
            name='ios_on_off',
            field=models.BooleanField(default=False),
        ),
    ]
