# Generated by Django 3.2 on 2023-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotargeting', '0001_initial'),
        ('shortcode', '0026_auto_20230901_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodeclass',
            name='template_geo',
            field=models.ManyToManyField(related_name='geothemplate', to='geotargeting.GeoThemplate'),
        ),
    ]
