# Generated by Django 3.2 on 2023-09-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0027_alter_shortcodeclass_template_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcodeclass',
            name='button_label',
            field=models.CharField(blank=True, max_length=520, null=True),
        ),
    ]
