# Generated by Django 3.2 on 2023-09-09 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortcode', '0027_alter_shortcodeclass_template_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255, unique=True)),
                ('settings_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('icon_svg', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkInBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_image', models.ImageField(upload_to='link_bio_profile_images/')),
                ('image', models.ImageField(upload_to='link_bio_images/')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('custome_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkinbio.customsettings')),
                ('links', models.ManyToManyField(to='shortcode.ShortcodeClass')),
                ('social_media_platforms', models.ManyToManyField(to='linkinbio.SocialMediaPlatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
