# Generated by Django 3.2 on 2023-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinbio',
            name='selected_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
