# Generated by Django 3.2 on 2023-09-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0027_alter_shortcodeclass_template_geo'),
        ('linkinbio', '0003_auto_20230909_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinbio',
            name='custome_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linkinbio.customsettings'),
        ),
        migrations.AlterField(
            model_name='linkinbio',
            name='links',
            field=models.ManyToManyField(null=True, to='shortcode.ShortcodeClass'),
        ),
        migrations.AlterField(
            model_name='linkinbio',
            name='social_media_platforms',
            field=models.ManyToManyField(null=True, to='linkinbio.SocialMediaPlatform'),
        ),
    ]
