# Generated by Django 3.2 on 2023-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0027_alter_shortcodeclass_template_geo'),
        ('linkinbio', '0004_auto_20230909_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinbio',
            name='links',
            field=models.ManyToManyField(to='shortcode.ShortcodeClass'),
        ),
        migrations.AlterField(
            model_name='linkinbio',
            name='social_media_platforms',
            field=models.ManyToManyField(to='linkinbio.SocialMediaPlatform'),
        ),
    ]
