# Generated by Django 3.2 on 2023-09-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0028_shortcodeclass_button_label'),
        ('linkinbio', '0008_auto_20230909_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInBioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('link_in_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkinbio.linkinbio')),
                ('shortcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortcode.shortcodeclass')),
            ],
            options={
                'unique_together': {('link_in_bio', 'shortcode')},
            },
        ),
    ]
