# Generated by Django 3.2 on 2023-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0009_linkinbiolink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkinbio',
            name='url_social',
        ),
        migrations.AddField(
            model_name='socialmediaplatform',
            name='url_social',
            field=models.URLField(blank=True, null=True),
        ),
    ]
