# Generated by Django 3.2 on 2023-09-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0011_remove_socialmediaplatform_url_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSocialProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_social', models.URLField(blank=True, null=True)),
                ('link_in_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkinbio.linkinbio')),
            ],
        ),
    ]
