# Generated by Django 3.2 on 2023-09-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0013_urlsocialprofiles_social_media_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinbio',
            name='social_media_platforms',
            field=models.ManyToManyField(blank=True, to='linkinbio.UrlSocialProfiles'),
        ),
    ]
