# Generated by Django 3.2 on 2023-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0015_auto_20230917_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinbiolink',
            name='is_aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
