# Generated by Django 3.2 on 2023-09-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0016_linkinbiolink_is_aktiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkinbio',
            name='links',
        ),
    ]
