# Generated by Django 3.2 on 2023-10-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0017_remove_linkinbio_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsettings',
            name='element_id',
        ),
        migrations.RemoveField(
            model_name='linkinbio',
            name='custome_settings',
        ),
        migrations.AddField(
            model_name='customsettings',
            name='link_in_bio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='linkinbio.linkinbio'),
            preserve_default=False,
        ),
    ]
