# Generated by Django 3.2 on 2023-08-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_encryptionkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptionKey',
        ),
    ]
