# Generated by Django 3.2 on 2023-08-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_encryptionkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_user',
            field=models.BooleanField(default=True),
        ),
    ]
