# Generated by Django 3.2 on 2023-09-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230827_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
