# Generated by Django 3.2 on 2023-08-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoThemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themplate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('land', models.CharField(blank=True, max_length=255, null=True)),
                ('themplate_region', models.CharField(blank=True, max_length=255, null=True)),
                ('themplate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
