# Generated by Django 3.2 on 2023-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_ipgeolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipgeolocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ipgeolocation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
