# Generated by Django 3.2 on 2023-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20230815_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipgeolocation',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
