# Generated by Django 3.2 on 2023-08-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_ipgeolocation_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipgeolocation',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ipgeolocation',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ipgeolocation',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
