# Generated by Django 3.2 on 2023-08-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20230815_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipgeolocation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
