# Generated by Django 3.2 on 2023-08-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0020_tag_user'),
        ('analytics', '0010_ipgeolocation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipgeolocation',
            name='shortcode',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='geolocations', to='shortcode.shortcodeclass'),
            preserve_default=False,
        ),
    ]
