# Generated by Django 3.2 on 2023-08-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_ipgeolocation_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipgeolocation',
            name='shortcode',
        ),
    ]
