# Generated by Django 3.2 on 2023-08-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0021_auto_20230817_1501'),
        ('analytics', '0013_ipgeolocation_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyclick',
            name='short_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_clicks', to='shortcode.shortcodeclass'),
        ),
    ]
