# Generated by Django 3.2 on 2023-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_alter_dailyclick_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipgeolocation',
            name='referrer',
            field=models.CharField(default='Unknown Referrer', max_length=255),
        ),
    ]
