# Generated by Django 3.2 on 2023-08-18 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0015_ipgeolocation_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('referrer', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
